name: Test CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: install
        run: yarn

      - name: test
        run: yarn test:coverage
        env:
          # 百度配置项
          BAIDU_APP_ID: ${{ secrets.BAIDU_APP_ID }}
          BAIDU_KEY: ${{ secrets.BAIDU_KEY }}

          # 有道配置项
          YOUDAO_COOKIE: ${{ secrets.YOUDAO_COOKIE }}
          YOUDAO_TOKEN: ${{ secrets.YOUDAO_TOKEN }}
          YOUDAO_USER_AGENT: ${{ secrets.YOUDAO_USER_AGENT }}
          YOUDAO_APP_ID: ${{ secrets.YOUDAO_APP_ID }}
          YOUDAO_KEY: ${{ secrets.YOUDAO_KEY }}

      - name: Generate coverage
        run: bash <(curl -s https://codecov.io/bash)
